name: Build, Test, and Release

on:
  push:
    branches: [ master ]

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4  # Upgrade to v4
      with:
        fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Use Node.js 22
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'
        cache: 'yarn'
        registry-url: 'https://registry.npmjs.org'
        scope: '@vepler'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Lint
      run: yarn lint

    - name: Build
      run: yarn build

    - name: Test
      env:
        ADMIN_API_KEY: ${{ secrets.ADMIN_API_KEY }}
      run: yarn test:coverage

    # Only run release step on push to master branch, not for PRs
    - name: Setup Git Identity for Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
    
    - name: Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: yarn semantic-release
